resource "tls_private_key" "pvtkey" {
  algorithm   = "RSA"
  rsa_bits = "4096"
}

resource "local_file" "key_details" {
    content     = tls_private_key.pvtkey.private_key_pem
    filename = "/root/key.txt"
}

resource "local_file" "whale" {
    filename = "/root/whale"
    depends_on = [
        local_file.krill,
    ]
}

resource "local_file" "krill" {
    filename = "/root/krill"
}

resource "random_pet" "my-pet" {

  length    = var.length 
}

output "pet-name" {
	
	value = random_pet.my-pet.id
	description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
    filename = "/root/message.txt"
    content = "Welcome to Kodekloud."
}

output "welcome_message" {
  value = local_file.welcome.content
}

resource "local_file" "key_data" {
        filename       = "/tmp/.pki/private_key.pem"
        content = tls_private_key.private_key.private_key_pem
        file_permission =  "0400"
}
resource "tls_private_key" "private_key" {
  algorithm   = "RSA"
  rsa_bits  = 4096
}
resource "tls_cert_request" "csr" {
  key_algorithm   = "ECDSA"
  private_key_pem = file("/tmp/.pki/private_key.pem")
  depends_on = [ local_file.key_data ]

  subject {
    common_name  = "flexit.com"
    organization = "FlexIT Consulting Services"
  }
}
